name: post_to_facebook
description: A Dart package for posting content to Facebook on behalf of a user or page.
version: 0.0.1
repository: https://github.com/thulotechnology/PostToFacebook
environment:
  sdk: ">=2.19.6 <3.0.0"

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

dependencies:
  http: ^0.13.5
  flutter:
    sdk: flutter
